[project]
name = "PyAiWrap"
version = "1.0.0"
description = "Neural network skeleton with dynamic layer construction from JSON"
authors = [
    {name = "Mateusz Kiełbus", email = "mateusz.kielbus.mk@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
    "torch==2.9.0",
    "torchvision==0.24.0",
    "matplotlib==3.10.7",
    "pandas>=2.2.3",
    "pillow==12.0.0",
    "tqdm==4.67.1",
    "numpy>=2.1.0",
    "opencv-python>=4.10.0",
    "scikit-image>=0.24.0",
    "python-docx==1.1.0",
    "lpips==0.1.4",
    "kornia==0.8.2",
    "kornia_rs==0.1.10",
    "monai>=1.5.1",
    "scikit-learn>=1.7.2"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Data Science :: Deep Learning", 
    "Programming :: Developers"
]
urls = {Homepage = "https://github.com/mkielbus/AI-in-Computer-Graphics-Labs"}

[project.optional-dependencies]
dev = [
    "pytest>=8.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true